### github-action-checkout-01.yml

name: test checkout-01
run-name: run github actions checkout
on:
  workflow_dispatch

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Print ls
        run: ls -al
        
      - name: Github Actions Checkout
        uses: actions/checkout@v4
        with:
          path: checkout-dir
          
      - name: Github Actions Checkout(others repo)
        uses: actions/checkout@v4
        with:
          repostiory: actions/checkout
          path: other-repo
          
      - run: ls -al
  
