### github-action-variable-04.yml
name: Test Github Actions variable-04
run-name: Github Actions input,output
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'name-to-big'
        required: true
        default: 'input'

jobs:
  input-data:
    runs-on: ubuntu-latest
    outputs:
      upper-name: ${{ steps.uppercase.outputs.result }}
    steps:
      - name: Print input data
        id: uppercase
        run: echo "result=$(echo '${{ github.event.inputs.name }}' | tr 'a-z' 'A-Z')" >> $GITHUB_OUTPUT

  output-data:
    needs: input-data
    runs-on: ubuntu-latest
    steps:
      - name: Print output data
        run: echo "Hello, ${{ needs.input-data.outputs.upper_name }}"
