### github-action-variable-01.yml


name: Test Github Actions variable-01
on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Friday

jobs:
  check-var:
    runs-on: ubuntu-latest
    env:
      MESSAGE: HELLO
    steps:
      - name: "It's a day!"
        if: ${{env.DAY_OF_WEEK == 'Thursday'}}
        run : echo "$MESSAGE Today is $DAY_OF_WEEK!"

  check-var2:
    runs-on: ubuntu-latest
    steps:
      - name: "It's a day!"
        run : echo "$MESSAGE Today is $DAY_OF_WEEK!"
  check-var3:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fruits: [Apple, Banna, Kiwi]
    steps:
      - name: "It's fruits!"
        run : echo "Hello, ${{ matrix.fruits }}"
