### github-action-variable-03.yml


name: Test Github Actions variable-03
run-name: Github Actions var,secret
on:
  push



jobs:
  check-vars-context:
    runs-on: ubuntu-latest
    steps:
      - name: VarTEST
        run: "Hello, ${{ vars.VAR_TEST }}"

  check-secret-context:
    runs-on: ubuntu-latest
    steps:
      - name: SecretTEST
        run: "Hello, ${{ secrets.SECRET_TEST }}"
